-- MySQL Script generated by MySQL Workbench
-- Mon Nov 19 01:46:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzaria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzaria` ;

-- -----------------------------------------------------
-- Table `Pizzaria`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Ingrediente` (
  `Ingrediente_id` INT NOT NULL AUTO_INCREMENT,
  `Ingrediente_nome` VARCHAR(45) NOT NULL,
  `Ingrediente_valor` FLOAT NOT NULL,
  `Ingrediente_estoque` INT NOT NULL,
  PRIMARY KEY (`Ingrediente_id`),
  UNIQUE INDEX `Ingrediente_nome_UNIQUE` (`Ingrediente_nome` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela com os ingredientes para o recheio da pizza';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Bebida` (
  `Bebida_id` INT NOT NULL AUTO_INCREMENT,
  `Bebida_nome` VARCHAR(45) NOT NULL,
  `Bebida_valor` FLOAT NOT NULL,
  `Bebida_estoque` INT NOT NULL,
  PRIMARY KEY (`Bebida_id`),
  UNIQUE INDEX `Ingrediente_nome_UNIQUE` (`Bebida_nome` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela com as bebidas disponíveis';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Borda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Borda` (
  `Borda_id` INT NOT NULL AUTO_INCREMENT,
  `Borda_nome` VARCHAR(45) NOT NULL,
  `Borda_valor` FLOAT NOT NULL,
  `Borda_estoque` INT NOT NULL,
  PRIMARY KEY (`Borda_id`),
  UNIQUE INDEX `Ingrediente_nome_UNIQUE` (`Borda_nome` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela com os ingredientes para o recheio da pizza';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Massa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Massa` (
  `Massa_id` INT NOT NULL AUTO_INCREMENT,
  `Massa_nome` VARCHAR(45) NOT NULL,
  `Massa_valor` FLOAT NOT NULL,
  `Massa_estoque` INT NOT NULL,
  PRIMARY KEY (`Massa_id`),
  UNIQUE INDEX `Massa_tamanho_UNIQUE` (`Massa_nome` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela com os tamanhos de Pizza';


-- -----------------------------------------------------
-- Table `Pizzaria`.`PizzaPronta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`PizzaPronta` (
  `PizzaPronta_id` INT NOT NULL AUTO_INCREMENT,
  `PizzaPronta_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PizzaPronta_id`),
  UNIQUE INDEX `Pizza_nome_UNIQUE` (`PizzaPronta_nome` ASC))
ENGINE = InnoDB
COMMENT = 'Armazena os ingredientes das Pizzas';


-- -----------------------------------------------------
-- Table `Pizzaria`.`PizzaPronta_Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`PizzaPronta_Ingrediente` (
  `Ingrediente_id` INT NOT NULL,
  `PizzaPronta_id` INT NOT NULL,
  PRIMARY KEY (`Ingrediente_id`, `PizzaPronta_id`),
  INDEX `fk_Ingrediente_Pizza_Ingrediente1_idx` (`Ingrediente_id` ASC),
  INDEX `fk_PizzaPronta_Ingrediente_PizzaPronta1_idx` (`PizzaPronta_id` ASC),
  CONSTRAINT `fk_Ingrediente_Pizza_Ingrediente1`
    FOREIGN KEY (`Ingrediente_id`)
    REFERENCES `Pizzaria`.`Ingrediente` (`Ingrediente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PizzaPronta_Ingrediente_PizzaPronta1`
    FOREIGN KEY (`PizzaPronta_id`)
    REFERENCES `Pizzaria`.`PizzaPronta` (`PizzaPronta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Liga as Pizzas a seus Ingredientes';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pedido` (
  `Pedido_id` INT NOT NULL AUTO_INCREMENT,
  `Pedido_valor` FLOAT NULL,
  `Pedido_mesa` VARCHAR(10) NULL,
  PRIMARY KEY (`Pedido_id`))
ENGINE = InnoDB
COMMENT = 'Armazena as Pizzas e Bebidas doPedido';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Gerente` (
  `Gerente_id` INT NOT NULL AUTO_INCREMENT,
  `Gerente_user` VARCHAR(45) NOT NULL,
  `Gerente_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Gerente_id`),
  UNIQUE INDEX `Gerente_user_UNIQUE` (`Gerente_user` ASC))
ENGINE = InnoDB
COMMENT = 'Tabela do gerente do négocio. \nAtualmente sem implementação.';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pizza` (
  `Pizza_id` INT NOT NULL AUTO_INCREMENT,
  `Pizza_nome` VARCHAR(45) NOT NULL,
  `Pizza_valor` FLOAT NOT NULL,
  `Borda_id` INT NOT NULL,
  `Massa_id` INT NOT NULL,
  PRIMARY KEY (`Pizza_id`),
  INDEX `fk_Pizza_Borda1_idx` (`Borda_id` ASC),
  INDEX `fk_Pizza_Massa1_idx` (`Massa_id` ASC),
  CONSTRAINT `fk_Pizza_Borda1`
    FOREIGN KEY (`Borda_id`)
    REFERENCES `Pizzaria`.`Borda` (`Borda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Massa1`
    FOREIGN KEY (`Massa_id`)
    REFERENCES `Pizzaria`.`Massa` (`Massa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Armazena os ingredientes das Pizzas';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Pedido_Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pedido_Pizza` (
  `Pedido_id` INT NOT NULL,
  `Pizza_id` INT NOT NULL,
  `Pedido_Pizza_qnt` INT NOT NULL,
  PRIMARY KEY (`Pedido_id`, `Pizza_id`),
  INDEX `fk_Pizza_Pedido_Pedido1_idx` (`Pedido_id` ASC),
  INDEX `fk_Pedido_Pizza_Pizza1_idx` (`Pizza_id` ASC),
  CONSTRAINT `fk_Pizza_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `Pizzaria`.`Pedido` (`Pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Pizza_Pizza1`
    FOREIGN KEY (`Pizza_id`)
    REFERENCES `Pizzaria`.`Pizza` (`Pizza_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Liga os pedidos as suas Pizzas';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Pedido_Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pedido_Bebida` (
  `Bebida_id` INT NOT NULL,
  `Pedido_id` INT NOT NULL,
  `Pedido_Bebida_qnt` INT NOT NULL,
  PRIMARY KEY (`Bebida_id`, `Pedido_id`),
  INDEX `fk_Bebida_Pedido_Pedido1_idx` (`Pedido_id` ASC),
  INDEX `fk_Bebida_Pedido_Bebida1_idx` (`Bebida_id` ASC),
  CONSTRAINT `fk_Bebida_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `Pizzaria`.`Pedido` (`Pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bebida_Pedido_Bebida1`
    FOREIGN KEY (`Bebida_id`)
    REFERENCES `Pizzaria`.`Bebida` (`Bebida_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Liga os pedidos a suas bebidas';


-- -----------------------------------------------------
-- Table `Pizzaria`.`Pizza_Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzaria`.`Pizza_Ingrediente` (
  `Pizza_id` INT NOT NULL,
  `Ingrediente_id` INT NOT NULL,
  PRIMARY KEY (`Pizza_id`, `Ingrediente_id`),
  INDEX `fk_Pizza_Ingrediente_Ingrediente1_idx` (`Ingrediente_id` ASC),
  INDEX `fk_Pizza_Ingrediente_Pizza1_idx` (`Pizza_id` ASC),
  CONSTRAINT `fk_Pizza_Ingrediente_Pizza1`
    FOREIGN KEY (`Pizza_id`)
    REFERENCES `Pizzaria`.`Pizza` (`Pizza_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Ingrediente_Ingrediente1`
    FOREIGN KEY (`Ingrediente_id`)
    REFERENCES `Pizzaria`.`Ingrediente` (`Ingrediente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Pizzaria' IDENTIFIED BY 'stanloona';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `Pizzaria`.* TO 'Pizzaria';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
